
platform :ios, '9.3'
use_frameworks!

target 'VideoEditorSDK_Example' do
  pod 'VideoEditorSDK', :path => '../'
  pod 'GPUImage'

  target 'VideoEditorSDK_Tests' do
    inherit! :search_paths

    
  end
end
